//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PronacaPlugin.WsRp3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.approuter.com/connectors/wsdl", ConfigurationName="WsRp3.ImportacionPesosAriesPort")]
    public interface ImportacionPesosAriesPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ImportacionPesosAries no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PronacaPlugin.WsRp3.ImportacionPesosAriesResponse ImportacionPesosAries(PronacaPlugin.WsRp3.ImportacionPesosAriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PronacaPlugin.WsRp3.ImportacionPesosAriesResponse> ImportacionPesosAriesAsync(PronacaPlugin.WsRp3.ImportacionPesosAriesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ln.gesalm.integracion.pronaca.com.ec")]
    public partial class validarPeso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlFileBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xmlFileBase64 {
            get {
                return this.xmlFileBase64Field;
            }
            set {
                this.xmlFileBase64Field = value;
                this.RaisePropertyChanged("xmlFileBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ln.gesalm.integracion.pronaca.com.ec")]
    public partial class validarPesoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string validarPesoResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string validarPesoResult {
            get {
                return this.validarPesoResultField;
            }
            set {
                this.validarPesoResultField = value;
                this.RaisePropertyChanged("validarPesoResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportacionPesosAriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ln.gesalm.integracion.pronaca.com.ec", Order=0)]
        public PronacaPlugin.WsRp3.validarPeso validarPeso;
        
        public ImportacionPesosAriesRequest() {
        }
        
        public ImportacionPesosAriesRequest(PronacaPlugin.WsRp3.validarPeso validarPeso) {
            this.validarPeso = validarPeso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportacionPesosAriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ln.gesalm.integracion.pronaca.com.ec", Order=0)]
        public PronacaPlugin.WsRp3.validarPesoResponse validarPesoResponse;
        
        public ImportacionPesosAriesResponse() {
        }
        
        public ImportacionPesosAriesResponse(PronacaPlugin.WsRp3.validarPesoResponse validarPesoResponse) {
            this.validarPesoResponse = validarPesoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportacionPesosAriesPortChannel : PronacaPlugin.WsRp3.ImportacionPesosAriesPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportacionPesosAriesPortClient : System.ServiceModel.ClientBase<PronacaPlugin.WsRp3.ImportacionPesosAriesPort>, PronacaPlugin.WsRp3.ImportacionPesosAriesPort {
        
        public ImportacionPesosAriesPortClient() {
        }
        
        public ImportacionPesosAriesPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportacionPesosAriesPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportacionPesosAriesPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportacionPesosAriesPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PronacaPlugin.WsRp3.ImportacionPesosAriesResponse PronacaPlugin.WsRp3.ImportacionPesosAriesPort.ImportacionPesosAries(PronacaPlugin.WsRp3.ImportacionPesosAriesRequest request) {
            return base.Channel.ImportacionPesosAries(request);
        }
        
        public PronacaPlugin.WsRp3.validarPesoResponse ImportacionPesosAries(PronacaPlugin.WsRp3.validarPeso validarPeso) {
            PronacaPlugin.WsRp3.ImportacionPesosAriesRequest inValue = new PronacaPlugin.WsRp3.ImportacionPesosAriesRequest();
            inValue.validarPeso = validarPeso;
            PronacaPlugin.WsRp3.ImportacionPesosAriesResponse retVal = ((PronacaPlugin.WsRp3.ImportacionPesosAriesPort)(this)).ImportacionPesosAries(inValue);
            return retVal.validarPesoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PronacaPlugin.WsRp3.ImportacionPesosAriesResponse> PronacaPlugin.WsRp3.ImportacionPesosAriesPort.ImportacionPesosAriesAsync(PronacaPlugin.WsRp3.ImportacionPesosAriesRequest request) {
            return base.Channel.ImportacionPesosAriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PronacaPlugin.WsRp3.ImportacionPesosAriesResponse> ImportacionPesosAriesAsync(PronacaPlugin.WsRp3.validarPeso validarPeso) {
            PronacaPlugin.WsRp3.ImportacionPesosAriesRequest inValue = new PronacaPlugin.WsRp3.ImportacionPesosAriesRequest();
            inValue.validarPeso = validarPeso;
            return ((PronacaPlugin.WsRp3.ImportacionPesosAriesPort)(this)).ImportacionPesosAriesAsync(inValue);
        }
    }
}
